#!/bin/bash
exec /u/nlp/packages/scala/scala-2.11.0/bin/scala -cp /u/nlp/packages/qry/lib/qry.jar:$JAVANLP_HOME/projects/core/classes:$JAVANLP_HOME/projects/more/classes:$JAVANLP_HOME/projects/more/lib/typesafe-config-1.0.0.jar:$JAVANLP_HOME/projects/research/classes "$0" "$@"
!#
import Qry._  // Qry Core
import Stanford._  // Utilities for Stanford

using("/afs/cs.stanford.edu/u/nayakne/NLP-HOME/scr/tiny-lana/train/runData/")
using("pbs")
PBS.name     = "runTest"
PBS.queue    = Queue.NLP
PBS.priority = Priority.NORMAL
PBS.cores    = 1

//parallel(<# cores>)

submit("torch-lua"
  ->("oneLayer_proto.lua")
  -("inputSize", "100")
  -("hiddenFactor", "0.5" & "0.75" & "1.0")
  -("learningRate", "0.1" & "0.05" & "0.01")
  -("regCoeff", "0" & "0.001" & "0.0003" & "0.0001")
  -("protoWeight", "0.1" & "0.01" & "0.03")
  -("endLimit", "20")
  -("pairSet", "EH")
  -("printFreq", "1")
)
